/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Symbols */
        get: operations["list_symbols_runs__run_id__symbols_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/symbols/{symbol}/bbo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bbo */
        get: operations["get_bbo_runs__run_id__symbols__symbol__bbo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/symbols/{symbol}/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trades */
        get: operations["get_trades_runs__run_id__symbols__symbol__trades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BboBucket */
        BboBucket: {
            /**
             * Bucket Ts Ns
             * @description Start of the time bucket (ns since midnight ET)
             */
            bucket_ts_ns: number;
            /**
             * Ts
             * @description Bucket start formatted as HH:MM:SS.fffffffff
             */
            ts: string;
            /**
             * Bid Open
             * @description First bid price observed in this bucket
             */
            bid_open: number;
            /**
             * Bid Close
             * @description Last bid price observed in this bucket
             */
            bid_close: number;
            /** Ask Open */
            ask_open: number;
            /** Ask Close */
            ask_close: number;
            /**
             * Spread Avg
             * @description Mean of (ask - bid) across BBO updates in this bucket
             */
            spread_avg: number;
            /**
             * Samples
             * @description Number of underlying BBO updates aggregated into this bucket
             */
            samples: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description 'ok' when the service is up
             */
            status: string;
            /**
             * Data Dir Exists
             * @description Whether the configured data directory is reachable
             */
            data_dir_exists: boolean;
            /**
             * Runs Count
             * @description Number of run-id directories detected on disk
             */
            runs_count: number;
        };
        /** RunDetail */
        RunDetail: {
            /** Run Id */
            run_id: string;
            /** Bbo Rows */
            bbo_rows: number;
            /** Trades Rows */
            trades_rows: number;
            /** Symbols */
            symbols: number;
            /**
             * First Ts Ns
             * @description Earliest timestamp in this run (ns since midnight ET)
             */
            first_ts_ns: number;
            /**
             * First Ts
             * @description Earliest timestamp formatted as HH:MM:SS.fffffffff
             */
            first_ts: string;
            /**
             * Last Ts Ns
             * @description Latest timestamp in this run (ns since midnight ET)
             */
            last_ts_ns: number;
            /**
             * Last Ts
             * @description Latest timestamp formatted as HH:MM:SS.fffffffff
             */
            last_ts: string;
            /**
             * Files
             * @description Map of filename -> size in bytes for this run
             */
            files: {
                [key: string]: number;
            };
        };
        /** RunSummary */
        RunSummary: {
            /**
             * Run Id
             * @description Trading day in YYYY-MM-DD format
             * @example 2019-01-30
             */
            run_id: string;
            /**
             * Bbo Rows
             * @description Number of BBO change rows
             */
            bbo_rows: number;
            /**
             * Trades Rows
             * @description Number of trade rows
             */
            trades_rows: number;
            /**
             * Symbols
             * @description Distinct symbols present in trades.csv
             */
            symbols: number;
            /**
             * Size Bytes
             * @description Total on-disk size of CSV + Parquet files for this run
             */
            size_bytes: number;
        };
        /** SymbolStat */
        SymbolStat: {
            /** Symbol */
            symbol: string;
            /**
             * Trades
             * @description Number of trade prints for this symbol
             */
            trades: number;
            /**
             * Shares
             * @description Total shares traded
             */
            shares: number;
            /**
             * Vwap
             * @description Volume-weighted average price across all trades
             */
            vwap: number;
            /** First Price */
            first_price: number;
            /** Last Price */
            last_price: number;
            /** First Ts Ns */
            first_ts_ns: number;
            /** First Ts */
            first_ts: string;
            /** Last Ts Ns */
            last_ts_ns: number;
            /** Last Ts */
            last_ts: string;
        };
        /** Trade */
        Trade: {
            /** Ts Ns */
            ts_ns: number;
            /** Ts */
            ts: string;
            /** Price */
            price: number;
            /** Shares */
            shares: number;
        };
        /** TradesPage */
        TradesPage: {
            /**
             * Total
             * @description Total trades matching the filter, before pagination
             */
            total: number;
            /** Items */
            items: components["schemas"]["Trade"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trading day in YYYY-MM-DD format */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_symbols_runs__run_id__symbols_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Trading day in YYYY-MM-DD format */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolStat"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_bbo_runs__run_id__symbols__symbol__bbo_get: {
        parameters: {
            query?: {
                /** @description Window start (ns since midnight ET). Defaults to start of day or regular open. */
                from_ts_ns?: number | null;
                /** @description Window end (ns since midnight ET, exclusive). Defaults to end of day or regular close. */
                to_ts_ns?: number | null;
                /** @description Bucket size for downsampling */
                resolution?: "100ms" | "1s" | "1m" | "5m";
                /** @description If true, restrict to 09:30:00–16:00:00 ET regular session */
                regular_hours?: boolean;
            };
            header?: never;
            path: {
                /** @description Trading day in YYYY-MM-DD format */
                run_id: string;
                /** @description Stock ticker (uppercase, up to 8 chars) */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BboBucket"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trades_runs__run_id__symbols__symbol__trades_get: {
        parameters: {
            query?: {
                /** @description Window start (ns since midnight ET) */
                from_ts_ns?: number;
                /** @description Window end (ns since midnight ET, exclusive) */
                to_ts_ns?: number;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Trading day in YYYY-MM-DD format */
                run_id: string;
                /** @description Stock ticker (uppercase, up to 8 chars) */
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradesPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
